<a href="https://colab.research.google.com/github/deveshsingh14/DL-NLP/blob/main/Single_layer_ANN_classfication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
from tensorflow.keras import Sequential #helps to initialize ANN
from tensorflow.keras.layers import Dense #help to create layers
from sklearn.metrics import classification_report


In [ ]:
#!pip install openpyxl
#!pip install xlrd
df=pd.read_excel("Churn_Modelling.xlsx")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
x=df.iloc[:,3:-1].values #convert df into numpy array
y=df.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
#fit: calculation/formula
#transform: applying calculation on data

In [ ]:
x


array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
le1=LabelEncoder()
x[:,2]=le1.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [ ]:
#step-1: Initialize model
ann=Sequential()
#step2 add layers to model
ann.add(Dense(units=6,activation="relu")) #linear rectified unit i/p layer
ann.add(Dense(units=1,activation="sigmoid")) #o/p layer
#step 3:compile model/establishing connection between layers
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
#step 4:train model
ann.fit(xtrain,ytrain,batch_size=30,epochs=100)



Epoch 1/100
234/234 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7621
Epoch 2/100
234/234 [==============================] - 0s 2ms/step - loss: 0.4699 - accuracy: 0.7929
Epoch 3/100
234/234 [==============================] - 1s 3ms/step - loss: 0.4454 - accuracy: 0.7980
Epoch 4/100
234/234 [==============================] - 1s 3ms/step - loss: 0.4320 - accuracy: 0.8044
Epoch 5/100
234/234 [==============================] - 1s 3ms/step - loss: 0.4221 - accuracy: 0.8114
Epoch 6/100
234/234 [==============================] - 1s 3ms/step - loss: 0.4132 - accuracy: 0.8139
Epoch 7/100
234/234 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8209
Epoch 8/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3979 - accuracy: 0.8263
Epoch 9/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.8316
Epoch 10/100
234/234 [==============================] - 0s 2ms/step - loss: 0.3868 - accura

In [ ]:
#step: prediction
ypred=ann.predict(xtest)
ypred

94/94 [==============================] - 0s 1ms/step


array([[0.05445527],
       [0.08660734],
       [0.05962797],
       ...,
       [0.02060942],
       [0.08317656],
       [0.07211263]], dtype=float32)

In [ ]:
#step 6: set threshold
ypred=ypred>0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      2373
           1       0.78      0.45      0.57       627

    accuracy                           0.86      3000
   macro avg       0.83      0.71      0.75      3000
weighted avg       0.85      0.86      0.84      3000



In [ ]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logreg=LogisticRegression()
logreg.fit(xtrain,ytrain)
yp=logreg.predict(xtest)
print(classification_report(ytest,yp))

              precision    recall  f1-score   support

           0       0.82      0.97      0.89      2373
           1       0.64      0.18      0.28       627

    accuracy                           0.81      3000
   macro avg       0.73      0.58      0.59      3000
weighted avg       0.78      0.81      0.76      3000



In [ ]:
ann.history.history

{}